apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: cloudethix_kiran  
  labels:
    app: nginx
spec:
  replicas: 3
    selector:
      matchLabels:
         app: nginx
    template:
      metadata:
         labels:
          app: nginx
      spec:
       containers:
       - name: nginx
         image: hr1daya/cloudethix-nginix-kiran:latest
         ports:
         - containerPort: 80
